/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Incidente;

/**
 *
 * @author WISTAR
 */
public class IFrmPorBarrio extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmPorZonas
     */
    public IFrmPorBarrio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBarrios = new javax.swing.JComboBox<>();
        txtMostrarPorBarrio = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Incidencias Por Barrios");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Selccione la Zona");

        cmbBarrios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbBarrios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Juan", "El Ejido", "San Bartolo", " " }));
        cmbBarrios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBarriosItemStateChanged(evt);
            }
        });
        cmbBarrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMostrarPorBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(143, 143, 143)
                        .addComponent(cmbBarrios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBarrios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(txtMostrarPorBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBarriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarriosActionPerformed
        Incidente in= new Incidente();
        String barrio=(String)cmbBarrios.getSelectedItem();
        //if(barrio.equals("San Juan") /*&& barrio.equals(in.getIncidente())*/)
       // {
            txtMostrarPorBarrio.setText(in.getIncidente());
            txtMostrarPorBarrio.setText(in.getCallePri());
            txtMostrarPorBarrio.setText(in.getCalleSec());
       // }
    }//GEN-LAST:event_cmbBarriosActionPerformed

    private void cmbBarriosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBarriosItemStateChanged
        Incidente in= new Incidente();
       // String barrio=(String)cmbBarrios.getSelectedItem();
       // if(barrio.equals("San Juan") && barrio.equals(in.getIncidente()))
        //{
            txtMostrarPorBarrio.setText(in.getIncidente());
            txtMostrarPorBarrio.setText(in.getCallePri());
            txtMostrarPorBarrio.setText(in.getCalleSec());
       // }
    }//GEN-LAST:event_cmbBarriosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBarrios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMostrarPorBarrio;
    // End of variables declaration//GEN-END:variables
}
