/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.HistorialDeIncidentes;
import modelo.Incidente;

/**
 *
 * @author WISTAR
 */
public class MostrarPorIncidente extends javax.swing.JFrame {

    DefaultTableModel modelo;
    public MostrarPorIncidente() {
        initComponents();        
//        modelo = new DefaultTableModel();
//        modelo.addColumn("Incidente");
//        modelo.addColumn("Barrio");
//        modelo.addColumn("Calle principal");
//        modelo.addColumn("Calle Secundaria");
//        modelo.addColumn("Fecha");
//        this.jTablaPorIncidente.setModel(modelo);
//        ArrayList<Incidente> listaIncidentes = HistorialDeIncidentes.getInsatance().getListIncidentes();
//        for (int i = 0; i < listaIncidentes.size(); i++) {
//            String[] info = new String[6];
//            info[0] = listaIncidentes.get(i).getIncidente();
//            info[1] = listaIncidentes.get(i).getBarrio();
//            info[2] = listaIncidentes.get(i).getCallePri();
//            info[3] = listaIncidentes.get(i).getCalleSec();
//            info[4] = listaIncidentes.get(i).getFechaIncidente();
//            info[5] = listaIncidentes.get(i).getDescripcionIncidente();
//            modelo.addRow(info);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaPorIncidente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmbTipoIncidente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Incidentes Por Tipos");

        jTablaPorIncidente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Barrio", "Calle Principal", "Calle Secundaria", "Fecha", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jTablaPorIncidente);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese el tipo de Incidente:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbTipoIncidente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbTipoIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Robo", "Asalto", "Incendio", "Violencia Familiar", "Pelea Callejera", "Otros", " " }));
        cmbTipoIncidente.setToolTipText("");
        cmbTipoIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoIncidenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(cmbTipoIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTipoIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmMostrarIncidentes mostrar=new FrmMostrarIncidentes();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbTipoIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoIncidenteActionPerformed
        // TODO add your handling code here:
         modelo = new DefaultTableModel();
        modelo.addColumn("Incidente");
        modelo.addColumn("Barrio");
        modelo.addColumn("Calle principal");
        modelo.addColumn("Calle Secundaria");
        modelo.addColumn("Fecha");
        modelo.addColumn("Descripcion");
        this.jTablaPorIncidente.setModel(modelo);
        ArrayList<Incidente> listaIncidentes = HistorialDeIncidentes.getInsatance().getListIncidentes();
        String incidente=(String) cmbTipoIncidente.getSelectedItem();
        for (int i = 0; i < listaIncidentes.size(); i++) {            
            System.out.println(incidente);
            if(listaIncidentes.get(i).getIncidente().equalsIgnoreCase(incidente)){            
            String[] info = new String[6];
            info[0] = listaIncidentes.get(i).getIncidente();
            info[1] = listaIncidentes.get(i).getBarrio();
            info[2] = listaIncidentes.get(i).getCallePri();
            info[3] = listaIncidentes.get(i).getCalleSec();
            info[4] = listaIncidentes.get(i).getFechaIncidente();
            info[5] = listaIncidentes.get(i).getDescripcionIncidente();
            modelo.addRow(info);
           }            
        }
        
    }//GEN-LAST:event_cmbTipoIncidenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarPorIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarPorIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarPorIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPorIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarPorIncidente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmbTipoIncidente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTablaPorIncidente;
    // End of variables declaration//GEN-END:variables
}
