/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.HistorialDeIncidentes;
import modelo.Incidente;

/**
 *
 * @author WISTAR
 */
public class MostrarPorBarrios extends javax.swing.JFrame {

    DefaultTableModel modelo;
    public MostrarPorBarrios() {
        initComponents();        
//        modelo = new DefaultTableModel();
//        modelo.addColumn("Incidente");
//        modelo.addColumn("Barrio");
//        modelo.addColumn("Calle principal");
//        modelo.addColumn("Calle Secundaria");
//        modelo.addColumn("Fecha");
//        this.jTableIncidentesPorBarrios.setModel(modelo);
//        ArrayList<Incidente> listaIncidentes = HistorialDeIncidentes.getInsatance().getListIncidentes();
//        for (int i = 0; i < listaIncidentes.size(); i++) {
//            String[] info = new String[6];
//            info[0] = listaIncidentes.get(i).getIncidente();
//            info[1] = listaIncidentes.get(i).getBarrio();
//            info[2] = listaIncidentes.get(i).getCallePri();
//            info[3] = listaIncidentes.get(i).getCalleSec();
//            info[4] = listaIncidentes.get(i).getFechaIncidente();
//            info[5] = listaIncidentes.get(i).getDescripcionIncidente();
//            modelo.addRow(info);
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBarrios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIncidentesPorBarrios = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Incidentes Por Barrios");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Selccione la Zona");

        cmbBarrios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbBarrios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "La Merced", "San Roque", "La Victoria", "San Diego", "González Suárez", "San Sebastián", "Panecillo", "San Blas", "La Tola", "San Marcos", "La Loma", "La Recoleta", "La Sena" }));
        cmbBarrios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBarriosItemStateChanged(evt);
            }
        });
        cmbBarrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarriosActionPerformed(evt);
            }
        });

        jTableIncidentesPorBarrios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incidente", "Calle Principal", "Calle Secundaria", "Fecha", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jTableIncidentesPorBarrios);

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(143, 143, 143)
                .addComponent(cmbBarrios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBarrios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBarriosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBarriosItemStateChanged
        
    }//GEN-LAST:event_cmbBarriosItemStateChanged

    private void cmbBarriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarriosActionPerformed
//        DefaultTableModel modelo;        
        modelo = new DefaultTableModel();
        modelo.addColumn("Incidente");
        modelo.addColumn("Barrio");
        modelo.addColumn("Calle principal");
        modelo.addColumn("Calle Secundaria");
        modelo.addColumn("Fecha");
        modelo.addColumn("Descripcion");
        this.jTableIncidentesPorBarrios.setModel(modelo);
        ArrayList<Incidente> listaIncidentes = HistorialDeIncidentes.getInsatance().getListIncidentes();
        String barrio=(String) cmbBarrios.getSelectedItem();
        for (int i = 0; i < listaIncidentes.size(); i++) {            
            System.out.println(barrio);
            if(listaIncidentes.get(i).getBarrio().equalsIgnoreCase(barrio)){            
            String[] info = new String[6];
            info[0] = listaIncidentes.get(i).getIncidente();
            info[1] = listaIncidentes.get(i).getBarrio();
            info[2] = listaIncidentes.get(i).getCallePri();
            info[3] = listaIncidentes.get(i).getCalleSec();
            info[4] = listaIncidentes.get(i).getFechaIncidente();
            info[5] = listaIncidentes.get(i).getDescripcionIncidente();
            modelo.addRow(info);
           }            
        }
        
        
    }//GEN-LAST:event_cmbBarriosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMostrarIncidentes mostrar=new FrmMostrarIncidentes();
        mostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarPorBarrios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarPorBarrios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarPorBarrios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPorBarrios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarPorBarrios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    public javax.swing.JComboBox<String> cmbBarrios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableIncidentesPorBarrios;
    // End of variables declaration//GEN-END:variables
}
